######################################################################
# Automatically generated by qmake (3.0) ?? 2? 11 20:34:01 2015
######################################################################

TEMPLATE = app
TARGET = opmapcontrol_demo
CONFIG  += release
CONFIG  -= debug_and_release
QT    += core gui widgets opengl sql svg network


UI_DIR       = ./build
MOC_DIR      = ./build
OBJECTS_DIR  = ./build


HEADERS += \
    MapWidget.h \
    UAS_types.h \
    MapWidget_TestWindow.h

SOURCES += \
    MapWidget.cpp \
    UAS_types.cpp \
    MapWidget_TestWindow.cpp \
    opmapcontrol_demo.cpp


################################################################################
# opmapcontrol
################################################################################
OPMAPCONTROL_DIR = ..
INCLUDEPATH +=  $$OPMAPCONTROL_DIR/src \
                $$OPMAPCONTROL_DIR/src/platform \
                $$OPMAPCONTROL_DIR/src/cache \
                $$OPMAPCONTROL_DIR/src/providers \
                $$OPMAPCONTROL_DIR/src/engine \
                $$OPMAPCONTROL_DIR/src/engine/projections \
                $$OPMAPCONTROL_DIR/src/ui
LIBS += $$OPMAPCONTROL_DIR/libopmapwidget.a
RESOURCES   += $$OPMAPCONTROL_DIR/src/ui/mapresources.qrc
